#!/bin/sh

# Hermes Android Client - Gradle Wrapper Script
# This file is part of the Hermes Android project

##############################################################################
#
#   IMPORTANT: Do not edit this file!
#
#   This is a generated file that will be regenerated by Gradle.
#   Any changes made to it will be overwritten the next time Gradle is run.
#
##############################################################################

# Save the current directory
DEFAULT_JVM_OPTS="-Xmx64m -Xms64m"
JAVA_CMD="java"
SAVE_DIR=$(pwd)

# Try to set JAVA_HOME if not set
if [ -z "$JAVA_HOME" ]; then
    JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java) 2>/dev/null))) 2>/dev/null || \
    JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java) 2>/dev/null))) 2>/dev/null
fi

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$(uname -s)" in
    CYGWIN* ) cygwin=true ;; 
    Darwin* ) darwin=true ;; 
    MSYS* | MINGW* ) msys=true ;; 
    NonStop* ) nonstop=true ;;
esac

CLASSPATH=$JAVA_HOME/lib/tools.jar

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] && [ -x "$JAVA_HOME/bin/java" ]; then
    JAVA_CMD="$JAVA_HOME/bin/java"
else
    JAVA_CMD="java"
fi

# Make it work in Cygwin as well
if $cygwin; then
    JAVA_CMD=$(cygpath --windows "$JAVA_CMD")
fi

# Look for Java in the PATH
if ! type "$JAVA_CMD" >/dev/null 2>&1; then
    echo "Java not found. Please install Java and set JAVA_HOME."
    exit 1
fi

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

# collect all arguments for the java command following the shell quoting and substitution rules
eval set -- $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS "\"-Dorg.gradle.appname=$APP_BASE_NAME\"" -classpath "\"$CLASSPATH\"" org.gradle.wrapper.GradleWrapperMain "$@"

# by default we should be in the correct directory, but when run from Finder on Mac, the cwd is wrong
if [ "$(uname)" = "Darwin" ] && [ "$SAVE_DIR" != "$(pwd)" ]; then
    cd "$SAVE_DIR"
fi

# workaround for bug in JDK 6 on Mac OS X that causes shell script to hang when run from Finder
if $darwin; then
    trap 'exit 0' SIGINT SIGTERM
fi

# Note: This is a simplified version. The actual Gradle wrapper script is more complex.
# For GitHub Actions, the wrapper will be downloaded automatically.
echo "Gradle wrapper placeholder - will be downloaded by GitHub Actions"
